#!/usr/bin/env python3
"""
run_metal.py -- fixed-effect (inverse-variance) meta-analysis of QC'd cohort
files with METAL, one meta per PHENOTYPE_STRATUM.

WHAT IT DOES
    1. Groups the QC'd cohort files by a key parsed from their filename
       (phenotype + stratum). Assuming these are named as such?? Or Drew can remap to these. Cohorts that share a key are meta-analysed
       together.
    2. Writes a METAL command script per group (SCHEME STDERR = fixed-effect,
       inverse-variance weighted).
    3. Runs METAL (with --run) outputs results as
       gzipped meta/<PHENO>_<STRATUM>.tsv.gz.

SAFE BY DEFAULT: without --run it only parses filenames, writes the grouping
manifest (meta/metal_groups.tsv) and the METAL scripts, as a check before running. 

RESUMABLE: a group whose final meta/<key>.tsv.gz already exists is skipped
(unless --force).

GROUPING
    Strata recognised: ALL EUR AFR AMR EAS SAS MALE FEMALE
    
    Default: assumes files are named  <cohort>_<pheno>_<stratum>. The cohort tag is the
    first token (no underscores or dots in it) and is ignored; the key is
    <pheno>_<stratum>, with the stratum at the END of the basename, e.g.
        biobank_ATOPIC_DERM_EUR.tsv.gz     -> ATOPIC_DERM_EUR
        cohort_PSORIASIS_ALL.txt.gz        -> PSORIASIS_ALL    
USAGE
    # 1) check the grouping (writes manifest + scripts, runs nothing)
    python3 run_metal.py --in qc --out meta
    # 2) run!!
    python3 run_metal.py --in qc --out meta --run --metal ./metal --threads 4
"""

import argparse
import glob
import gzip
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import OrderedDict
 
STRATA = ["ALL", "EUR", "AFR", "AMR", "EAS", "SAS", "MALE", "FEMALE"]
 
# standard column names in the QC'd inputs (what qc_munge.R writes)
COL_MARKER = "SNP_ID"
COL_EA     = "Effect_allele"
COL_NEA    = "Non-effect_allele"
COL_BETA   = "Beta"
COL_SE     = "SE"
COL_P      = "P-value"
COL_FREQ   = "Effect_AF"
 
DEFAULT_GROUP_RE = (
    r"^(?P<cohort>[^_.]+)[_.](?P<pheno>.+)_(?P<stratum>" + "|".join(STRATA) + r")$"
)
 
def basename_stem(path):
    b = os.path.basename(path)
    return re.sub(r"\.(tsv|txt|csv)(\.gz)?$", "", b, flags=re.I)
 
 
def discover(indir):
    files = []
    for pat in ("*.tsv.gz", "*.txt.gz", "*.tsv", "*.txt"):
        files += glob.glob(os.path.join(indir, pat))
    files = [f for f in files if not os.path.basename(f).startswith("._")]
    return sorted(set(files))
 
 
def group_files(files, group_re):
    rx = re.compile(group_re)
    groups, unmatched = OrderedDict(), []
    for f in files:
        m = rx.match(basename_stem(f))
        if not m:
            unmatched.append(f)
            continue
        gd = m.groupdict()
        pheno, stratum = gd.get("pheno"), gd.get("stratum")
        if not pheno or not stratum:
            key = m.group(0)
        else:
            key = f"{pheno}_{stratum}"
        groups.setdefault(key, []).append(f)
    return groups, unmatched
 
 
def write_manifest(path, groups, unmatched):
    with open(path, "w") as fh:
        fh.write("group_key\tn_cohorts\tcohort_files\n")
        for key, members in groups.items():
            fh.write(f"{key}\t{len(members)}\t"
                     f"{','.join(os.path.basename(m) for m in members)}\n")
        for f in unmatched:
            fh.write(f"UNMATCHED\t0\t{os.path.basename(f)}\n")
 
 
def write_metal_script(script_path, member_plain, out_prefix,
                       heterogeneity=False, genomic_control=False):
    """Emit a METAL command script. member_plain are DECOMPRESSED file paths
    (METAL cannot read gzip). Columns are whitespace/tab tokens with no spaces,
    so the METAL default whitespace separator parses them fine."""
    lines = [
        "# fixed-effect inverse-variance meta-analysis (generated by run_metal.py)",
        "SCHEME   STDERR",
        "AVERAGEFREQ ON",
        "MINMAXFREQ  ON",
    ]
    if genomic_control:
        lines.append("GENOMICCONTROL ON")
    lines += [
        f"MARKER    {COL_MARKER}",
        f"ALLELE    {COL_EA} {COL_NEA}",
        f"FREQLABEL {COL_FREQ}",
        f"EFFECT    {COL_BETA}",
        f"STDERR    {COL_SE}",
        f"PVALUE    {COL_P}",
        "",
    ]
    for m in member_plain:
        lines.append(f"PROCESS  {m}")
    lines += [
        "",
        f"OUTFILE  {out_prefix} .tbl",
        "ANALYZE HETEROGENEITY" if heterogeneity else "ANALYZE",
        "QUIT",
        "",
    ]
    with open(script_path, "w") as fh:
        fh.write("\n".join(lines))
 
 
def find_tbl(out_prefix):
    hits = sorted(glob.glob(out_prefix + "*.tbl"))
    return hits[-1] if hits else None
 
 
def gzip_tbl(tbl_path, final_path):
    """Copy the METAL .tbl unchanged into a gzipped file; return variant count."""
    n = 0
    with open(tbl_path, "rb") as fi, gzip.open(final_path, "wb", compresslevel=6) as fo:
        for line in fi:
            fo.write(line)
            n += 1
    return max(n - 1, 0)   # minus header
 
 
def decompress_to(src, dst):
    if src.endswith(".gz"):
        with gzip.open(src, "rb") as fi, open(dst, "wb") as fo:
            shutil.copyfileobj(fi, fo)
    else:
        shutil.copy2(src, dst)
 
 
def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--in", dest="indir", default="qc",
                    help="directory of QC'd cohort files (default: qc)")
    ap.add_argument("--out", dest="outdir", default="meta",
                    help="output directory for meta files (default: meta)")
    ap.add_argument("--metal", default="metal", help="METAL binary (default: metal on PATH)")
    ap.add_argument("--group-regex", default=DEFAULT_GROUP_RE,
                    help="regex with named groups 'pheno' and 'stratum'")
    ap.add_argument("--run", action="store_true",
                    help="actually run METAL (default: dry-run: scripts+manifest only)")
    ap.add_argument("--force", action="store_true", help="rebuild groups whose output exists")
    ap.add_argument("--threads", type=int, default=1,
                    help="parallel groups to run at once (default 1)")
    ap.add_argument("--heterogeneity", action="store_true",
                    help="add ANALYZE HETEROGENEITY (I^2 etc. in the .tbl)")
    ap.add_argument("--genomic-control", action="store_true",
                    help="apply METAL GENOMICCONTROL")
    ap.add_argument("--min-cohorts", type=int, default=1,
                    help="skip a group with fewer than this many cohorts (default 1)")
    ap.add_argument("--keep-tmp", action="store_true",
                    help="keep decompressed inputs and raw .tbl files")
    args = ap.parse_args()
 
    files = discover(args.indir)
    if not files:
        sys.exit(f"No QC'd files found in {args.indir}")
    groups, unmatched = group_files(files, args.group_regex)
 
    os.makedirs(args.outdir, exist_ok=True)
    scripts_dir = os.path.join(args.outdir, "metal_scripts"); os.makedirs(scripts_dir, exist_ok=True)
    raw_dir     = os.path.join(args.outdir, "metal_raw");     os.makedirs(raw_dir, exist_ok=True)
    manifest = os.path.join(args.outdir, "metal_groups.tsv")
    write_manifest(manifest, groups, unmatched)
 
    print(f"Discovered {len(files)} QC'd file(s) -> {len(groups)} group(s).")
    for key, members in groups.items():
        print(f"  {key}: {len(members)} cohort(s)")
    if unmatched:
        print(f"  !! {len(unmatched)} file(s) did not match the grouping regex "
              f"(listed as UNMATCHED in {manifest}); adjust --group-regex.")
    print(f"Manifest: {manifest}")
 
    metal_bin = shutil.which(args.metal) or (args.metal if os.path.exists(args.metal) else None)
    if not args.run:
        # still write the scripts so they can be inspected / run by hand
        for key, members in groups.items():
            if len(members) < args.min_cohorts:
                continue
            sp = os.path.join(scripts_dir, f"{key}.metal")
            out_prefix = os.path.join(raw_dir, f"{key}_")
            # scripts reference the .gz directly for readability in dry-run;
            # the actual run rewrites them to point at decompressed temp files.
            write_metal_script(sp, [os.path.abspath(m) for m in members], out_prefix,
                               args.heterogeneity, args.genomic_control)
        print(f"\nDRY RUN: wrote {len(groups)} METAL script(s) to {scripts_dir}/.")
        print("Review the manifest, then re-run with --run to execute METAL.")
        if not metal_bin:
            print(f"(note: METAL binary '{args.metal}' not found on PATH — set --metal when you run.)")
        return
 
    if not metal_bin:
        sys.exit(f"METAL binary not found: {args.metal} (set --metal /path/to/metal)")
 
    tmp_root = tempfile.mkdtemp(prefix="metal_", dir=args.outdir)
    n_done = n_skip = n_fail = 0
    try:
        for key, members in groups.items():
            if len(members) < args.min_cohorts:
                print(f"[skip] {key}: {len(members)} < --min-cohorts {args.min_cohorts}")
                n_skip += 1; continue
            final_path = os.path.join(args.outdir, f"{key}.tsv.gz")
            if os.path.exists(final_path) and not args.force:
                print(f"[skip] {key} (output exists)"); n_skip += 1; continue
 
            # decompress cohort files for METAL
            gdir = os.path.join(tmp_root, key); os.makedirs(gdir, exist_ok=True)
            plain = []
            for m in members:
                d = os.path.join(gdir, basename_stem(m) + ".tsv")
                decompress_to(m, d); plain.append(d)
 
            sp = os.path.join(scripts_dir, f"{key}.metal")
            out_prefix = os.path.join(raw_dir, f"{key}_")
            write_metal_script(sp, plain, out_prefix,
                               args.heterogeneity, args.genomic_control)
 
            print(f"[metal] {key} ({len(members)} cohorts)")
            with open(sp) as fh:
                r = subprocess.run([metal_bin], stdin=fh,
                                   stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            log_path = os.path.join(raw_dir, f"{key}.metal.log")
            with open(log_path, "wb") as lf:
                lf.write(r.stdout)
            if r.returncode != 0:
                print(f"    [FAIL] METAL exit {r.returncode}; see {log_path}")
                n_fail += 1; continue
 
            tbl = find_tbl(out_prefix)
            if not tbl:
                print(f"    [FAIL] no .tbl produced; see {log_path}")
                n_fail += 1; continue
            try:
                n = gzip_tbl(tbl, final_path)
            except Exception as e:
                print(f"    [FAIL] gzip of METAL output: {e}"); n_fail += 1; continue
            print(f"    [ok] {os.path.basename(final_path)}  ({n:,} variants)")
            n_done += 1
 
            if not args.keep_tmp:
                shutil.rmtree(gdir, ignore_errors=True)
                os.remove(tbl)   # gzipped copy is now in the output dir
    finally:
        if not args.keep_tmp:
            shutil.rmtree(tmp_root, ignore_errors=True)
 
    print(f"\nDONE.  {n_done} meta-analyses, {n_skip} skipped, {n_fail} failed. "
          f"Output -> {args.outdir}/")
 
 
if __name__ == "__main__":
    main()

